# Generated by Django 2.2.1 on 2019-06-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20190606_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='PersonalProfile',
        ),
    ]
