# Generated by Django 2.2.1 on 2019-06-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20190606_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalprofile',
            old_name='user',
            new_name='person',
        ),
    ]
