# Generated by Django 2.2.1 on 2019-06-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20190607_0803'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalProfile',
            new_name='PersonProfile',
        ),
    ]
