# Generated by Django 2.2.1 on 2019-06-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20190605_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='avatar',
            field=models.ImageField(upload_to='avatars'),
        ),
    ]
