# Generated by Django 2.2.1 on 2019-06-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_auto_20190605_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='avatar',
            field=models.ImageField(default='avatars/def_ava.jpg', upload_to='avatars'),
        ),
    ]
