# Generated by Django 2.2.1 on 2019-07-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
