# Generated by Django 2.2.1 on 2019-06-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190613_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='creation',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='creation',
            new_name='pub_date',
        ),
    ]
