# Generated by Django 2.2.1 on 2019-06-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190613_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
