# Generated by Django 2.2.1 on 2019-06-14 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20190614_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('pub_date',)},
        ),
    ]
